services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: env.sample
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    env_file: env.sample
    depends_on:
      - postgres
    volumes:
      # Add external storage if you want to
      # - /path/to/external:/external
      - data:/var/www/html
      - type: tmpfs
        target: /tmp:exec
    environment:
      PHP_MEMORY_LIMIT: "4096M"
      PHP_UPLOAD_LIMIT: "1048576M"
      APACHE_BODY_LIMIT: "0"

  nextcloud-cron:
    image: nextcloud:latest
    restart: unless-stopped
    depends_on:
      - nextcloud
    volumes:
      - data:/var/www/html
    entrypoint: /cron.sh

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - nextcloud
    ports:
      - 80:80
      - 443:443
    volumes:
      - /path/to/nginx.conf:/etc/nginx/conf.d/default.conf
      - /path/to/cert.crt:/etc/ssl/certs/cert.crt
      - /path/to/cert.key:/etc/ssl/private/cert.key

volumes:
  data:
  db: